name: Daniel Cornock
url: https://www.danielcornock.co.uk
title: Daniel Cornock
description: Personal portfolio page of Daniel Cornock, a front end developer from Birmingham, United Kingdom.
permalink: /blog/:categories/:title
staticImgLocation: /assets/img/static
categories:
  - tutorials
  - general
comments: true
highlighter: rouge

collections:
  portfolio:
    output: true

defaults:
  - scope:
      path: ""
      type: "portfolio"
    values:
      layout: "portfolio"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

